[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
num-bigint = "0.4"
num-traits = "0.2.8"
priority-queue = "0.5.2"
regex = "1"
