name: advent_of_code_2022

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy,rustfmt
          default: true
          override: true

      - name: Build
        run: cargo +nightly build --all --release

      - name: Test
        # note: we don't handle errors here as the 'mikepenz/action-junit-report' below will fail if there
        #       was an error
        run: |
          cargo +nightly test -- -Z unstable-options --format json --report-time | tee results.json

      - name: Prepare junit report
        id: cargo_reporter 
        uses: innoq/action-cargo-test-report@main
        with:
          cargo-test-report-json: 'results.json'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@main
        if: always() # always run even if the previous step fails
        with:
          check_name: Test Report
          fail_on_failure: true
          require_tests: true
          summary: ${{ steps.cargo_reporter.outputs.summary }}

      - name: Static analysis
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Check code formatting
        run: cargo fmt -- --check
